language: node_js
sudo: false
node_js:
  - '0.10'
install:
  - npm update
  - npm install -g bower
  - bower update
cache:
  directories:
    - node_modules
    - bower_components
deploy:
  provider: heroku
  api_key:
    secure: pWgnbzutxqWigSVfFFvvCcfyNz8oVxPxmiZO7omj7IyfaJoAa6BkSM4+D5TSWG4RQ0R2EGTJDnlGQIf5M+QeNJ/bmBhb5IBdNHDAAkRERniu3N2LLC87jDziV3JJfba3wt8ckgbnru7P63oyKryNpbYO0MQkx9tn3x2Q+ORpCUo=
  app: troxel
  on:
    repo: chrmoritz/Troxel
