version: "{build}"

environment:
  matrix:
  - nodejs_version: "0.10" # node.js
  - nodejs_version: "1.0"  # io.js

matrix:
  allow_failures:
    - nodejs_version: "1.0"

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm update
  - npm install -g bower
  - bower update

test_script:
  - cmd: npm test

cache:
  - node_modules
  - bower_components

build: off
