version: "{build}"

environment:
  matrix:
  - nodejs_version: "0.12" # node.js
  - nodejs_version: "1.0"  # io.js

matrix:
  allow_failures:
    - nodejs_version: "1.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install

test_script:
  - npm test

cache:
  - bower_components

build: off
